app:
  host: 0.0.0.0 #绑定的IP
  port: 5000 #绑定的端口号
  temp_output: temp_output #输出缓存
  temp_image: temp_image #图像缓存
  jm_config: False #是否开启外置jm库配置,默认使用内置配置
jm: # 警告!下面是外置jm库配置,没事请勿修改
  dir_rule:
    base_dir: '' #图像缓存目录
  download:
    image:
      decode: true
      suffix: .jpg
  log: true
  plugins:
      after_album:
      - plugin: img2pdf
        kwargs:
          pdf_dir: '' #pdf输出目录
          filename_rule: Aid
      - plugin: zip
        kwargs:
          level: album
          filename_rule: Aid
          zip_dir: '' #zip输出目录
          delete_original_file: true
  version: '2.1'

